language: go

go:
- 1.7.4
install: true

env:
  matrix:
  - NAME=ons

script: CGO_ENABLED=0 go build

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: $NAME
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - thb.krkr+travis-oq@gmail.com
